version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: assessment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-12345678}
      MYSQL_DATABASE: ${DB_NAME:-assessment_platform}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1

volumes:
  mysql_data:
