spring:
  application:
    name: assessment-platform

  profiles:
    active: local

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/assessment_platform?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:hussainyawar140504@gmail.com}
    password: ${MAIL_PASSWORD:jshxmyarozabijxs}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  answer-key:
    secret: ${ANSWER_KEY_SECRET:}
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY:}
      model: ${GEMINI_MODEL:auto}
  jwt:
    secret: ${JWT_SECRET:YTJiM2M0ZDVlNmY3ZzhoOWkwajFrMmwzbTRuNW82cDdxOHI5czB0MXUydjN3NHg1eTZ6N2E4YjljMGQxZTJm}
    expiration-ms: 86400000

  otp:
    expiration-minutes: 5

server:
  port: 8080

logging:
  level:
    com.assessment.platform: DEBUG
